config/routes.rb
Pochipochi::Application.routes.draw do
  get 'log_in' => 'sessions#new', :as => 'log_in'
  get 'log_out' => 'sessions#destroy', :as => 'log_out'
  get 'sign_up' => 'users#new', :as => 'sign_up'

  match "/auth/:provider/callback" => 'sessions#create'
  resources :users
  resources :sessions
  resources :bookmarks

  root :to => "bookmarks#index"
end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  # default_scope :order => 'created_at DESC'
  # default paginate num(can override)
  paginates_per 10

  def self.search(search)
    if search
      where("title LIKE ?", "%#{search}%")
    else
      scoped
    end
  end
end

app/models/provider.rb
class Provider < ActiveRecord::Base
  belongs_to :user

  def self.create_with_omniauth(auth, user)
    create! do |provider|
      provider.name = auth["provider"]
      provider.uid = auth["uid"]
      provider.user_id = user.id
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :bookmarks
  has_many :providers
  before_save :encrypt_password

  attr_accessor :password
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :adjust_format_for_iphone
  helper_method :current_user

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def login_required
    redirect_to log_in_path unless current_user
  end

  def adjust_format_for_iphone
    request.format = :iphone if iphone_request?
  end

  def iphone_request?
    request.env["HTTP_USER_AGENT"] && request.env["HTTP_USER_AGENT"][/(Mobile\/.+Safari)/]
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  helper_method :sort_column, :sort_direction
  before_filter :login_required

  def index
    @bookmarks = current_user.bookmarks.search(params[:search]).
                                        order(sort_column + " " + sort_direction).
                                        page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @bookmarks }
      format.js   { render :json => @bookmarks.to_json }
      format.iphone # index.iphone.erb
    end
  end

  def show
    @bookmark = Bookmark.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @bookmark }
    end
  end

  def new
    @bookmark = Bookmark.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @bookmark }
    end
  end

  def edit
    @bookmark = Bookmark.find(params[:id])
  end

  def create
    @bookmark = current_user.bookmarks.build(params[:bookmark])

    respond_to do |format|
      if @bookmark.save
        format.html { redirect_to(@bookmark, :notice => 'Bookmark was successfully created.') }
        format.xml  { render :xml => @bookmark, :status => :created, :location => @bookmark }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @bookmark.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @bookmark = Bookmark.find(params[:id])

    respond_to do |format|
      if @bookmark.update_attributes(params[:bookmark])
        format.html { redirect_to(@bookmark, :notice => 'Bookmark was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @bookmark.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy

    respond_to do |format|
      format.html { redirect_to(bookmarks_url) }
      format.xml  { head :ok }
    end
  end

  private
  def sort_column
    Bookmark.column_names.include?(params[:sort]) ? params[:sort] : "title"
  end

  def sort_direction
    %w(asc desc).include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = if current_user
             create_provider
             message = "Create provider successfully."
             current_user
           else
             message = "Logged in successfully."
             find_user
           end

    if user
      session[:user_id] = user.id
      redirect_to root_url, :notice => message
    else
      flash.now.alert = 'Invaldid email or password'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to :action => "new", :notice => "Logged out"
  end

  private
  def find_user
    if params[:email] and params[:password]
      authenticate_by_password
    elsif request.env["omniauth.auth"]
      authenticate_by_provider
    end
  end

  def authenticate_by_password
    User.authenticate(params[:email], params[:password])
  end

  def authenticate_by_provider
    auth = request.env["omniauth.auth"]
    if provider = Provider.find_by_name_and_uid(auth["provider"], auth["uid"])
      provider.user
    else
      nil
    end
  end

  def create_provider
    auth = request.env["omniauth.auth"]
    Provider.create_with_omniauth(auth, current_user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title=nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, { :sort => column, :direction => direction }, { :class => css_class }
  end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookmarks/_bookmarks.html.erb
<table class="features-table">
  <tr>
    <th><<%= sortable "tag" -%></th>
    <th><<%= sortable "title" -%></th>
    <th><<%= sortable "description" -%></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <tfoot id="bookmark-template">
    <% @bookmarks.each do |bookmark| %>
      <tr class="bookmark">
        <td><%= bookmark.tag %></td>
        <td><%= link_to bookmark.title, bookmark.url, :target => '_blank' %></td>
        <td><%= bookmark.description %></td>
        <td><%= link_to 'Edit', edit_bookmark_path(bookmark) %></td>
        <td><%= link_to 'Destroy', bookmark, :confirm => 'Are you sure?', :method => :delete %></td>
      </tr>
    <% end %>
  </tfoot>
</table>

app/views/bookmarks/_bookmarks.iphone.erb
<ul data-role="listview" data-inset="row" data-theme="c" data-dividertheme="b">
  <li data-role="list-divider">your bookmarks</li>
  <% @bookmarks.each do |bookmark| %>
    <li><%= link_to bookmark.title, bookmark.url, :target => '_blank' %></li>
  <% end %>
</ul>

app/views/bookmarks/_boomarks.iphone.erb
<table class="features-table">
  <tr>
    <th><<%= sortable "tag" -%></th>
    <th><<%= sortable "title" -%></th>
    <th><<%= sortable "description" -%></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <tfoot id="bookmark-template">
    <% @bookmarks.each do |bookmark| %>
      <tr class="bookmark">
        <td><%= bookmark.tag %></td>
        <td><%= link_to bookmark.title, bookmark.url, :target => '_blank' %></td>
        <td><%= bookmark.description %></td>
        <td><%= link_to 'Edit', edit_bookmark_path(bookmark) %></td>
        <td><%= link_to 'Destroy', bookmark, :confirm => 'Are you sure?', :method => :delete %></td>
      </tr>
    <% end %>
  </tfoot>
</table>

app/views/bookmarks/_form.html.erb
<%= form_for(@bookmark) do |f| %>
  <% if @bookmark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bookmark.errors.count, "error") %> prohibited this bookmark from being saved:</h2>

      <ul>
      <% @bookmark.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :tag %><br />
    <%= f.text_field :tag %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bookmarks/edit.html.erb
<h1>Editing bookmark</h1>

<%= render 'form' %>

<%= link_to 'Show', @bookmark %> |
<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/index.html.erb
<script id="bookmarkListTemplate" type="text/x-jquery-tmpl">
  <tr class="bookmark">
    <td>${$data["bookmark"]["tag"]}</td>
    <td>${$data["bookmark"]["title"]}</td>
    <td>${$data["bookmark"]["description"]}</td>
  </tr>
</script>

<h2 class="title">Your bookmarks</h1>

<%= hidden_field_tag :sort, params[:sort] %>
<%= hidden_field_tag :direction, params[:direction] %>
<%= form_tag bookmarks_path, :method => 'get', :id => 'bookmarks_search' do %>
  <p>
    <%= text_field_tag(:search, params[:serach]) %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>


<%= paginate @bookmarks -%>

<div id="bookmarks">
  <%= render "bookmarks" %>
</div>

<%= link_to 'New Bookmark', new_bookmark_path %>

app/views/bookmarks/index.iphone.erb
<div data-role="header" align="center">
  Pochipochi
</div>

<div data-role="content">
  <%= form_tag '/bookmarks.iphone', :method => 'get', :id => 'bookmarks_search' do %>
    <%= text_field_tag(:search, params[:serach], :size=>30) %>
    <%= submit_tag "Search", :name => nil, 'data-role'=>:button, 'data-icon'=>:search, 'data-inline'=>:true %>
  <% end %>

  <%= render 'bookmarks' %>
</div>

<div data-role="footer" align="right">
  Created by pochi_black
</div>

app/views/bookmarks/index.js.erb
$("#bookmarks").html("<%= escape_javascript(render('bookmarks')) %>");

app/views/bookmarks/new.html.erb
<h1>New bookmark</h1>

<%= render 'form' %>

<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @bookmark.title %>
</p>

<p>
  <b>Url:</b>
  <%= @bookmark.url %>
</p>

<p>
  <b>Description:</b>
  <%= @bookmark.description %>
</p>

<p>
  <b>Tag:</b>
  <%= @bookmark.tag %>
</p>


<%= link_to 'Edit', edit_bookmark_path(@bookmark) %> |
<%= link_to 'Back', bookmarks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pochipochi</title>
  <%= stylesheet_link_tag :all %>
  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag "jquery.tmpl.min.js" %>
  <%= csrf_meta_tag %>
</head>
<body>

<% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, :id => "flash#{name}" %>
<% end -%>

<div class="user-navi">
  <% if current_user -%>
    Logged in as <%= current_user.email %>
    <%= link_to 'Create login with twitter', '/auth/twitter' %>
    <%= link_to 'Log out', log_out_path %>
  <% else -%>
    <%= link_to 'Sign up', sign_up_path %> or
    <%= link_to 'Log in', log_in_path %>
    <%= link_to 'Log in with twitter', '/auth/twitter' %>
    <%= link_to 'Log in with facebook', '/auth/facebook' %>
  <% end -%>
</div>

<div class="main">
  <%= yield %>
</div>

</body>
</html>

app/views/layouts/application.iphone.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <meta id="viewport" name="viewport" content="width=320; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;"/>
  <title>Pochipochi</title>
  <%= stylesheet_link_tag 'http://code.jquery.com/mobile/1.0a3/jquery.mobile-1.0a3.min.css' -%>
  <%= stylesheet_link_tag 'application.iphone.css' -%>
  <%= javascript_include_tag 'http://code.jquery.com/jquery-1.5.min.js' -%>
  <%= javascript_include_tag 'http://code.jquery.com/mobile/1.0a3/jquery.mobile-1.0a3.min.js' -%>
</head>
<body>
  <div data-role="page" data-theme="b">
    <%= yield %>
  </div>
</body>
</html>

app/views/users/new.html.erb
<h1>Users#new</h1>

<% form_for @user do |f| %>
  <% if @user.errors.any? -%>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages -%>
          <li><%= message -%></li>
        <% end-%>
      </ul>
    </div>
  <% end -%>

  <p>
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :password %><br/>
    <%= f.password_field :password %>
  </p>

  <p>
    <%= f.label :password_confirmation %><br/>
    <%= f.password_field :password_confirmation %>
  </p>

  <p class="button"><%= f.submit %></p>
<% end %>